In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
df=pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
#data preprocessing
#remove irrelevent columns
df=df.drop(['RowNumber','CustomerId','Surname'],axis=True)

In [5]:
## encode categorical data
label_encoder=LabelEncoder()
df['Gender']=label_encoder.fit_transform(df['Gender'])

In [6]:
df.head(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [7]:
## One hot encoding 
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder=OneHotEncoder()
geo_encoder=one_hot_encoder.fit_transform(df[['Geography']])

In [8]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [9]:
one_hot_encoder.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [10]:
geo_encoder_df = pd.DataFrame(
    geo_encoder.toarray(),
    columns=one_hot_encoder.get_feature_names_out(['Geography'])
)

In [11]:
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [12]:
# combine all the columns with the original data
df=pd.concat([df.drop('Geography',axis=1),geo_encoder_df],axis=1)

In [13]:
df.head(5)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [14]:
with open('regression_label_encoder.pkl', 'wb') as file:
    pickle.dump(label_encoder,file)

with open('regression_one_hot_encoder.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder,file)

In [15]:
## Divide the dataset into dependent and independent
X=df.drop('EstimatedSalary',axis=1)
y=df['EstimatedSalary']

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
##scale the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [17]:
with open('regression_scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Regression Problem statement

In [18]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [19]:
## Verify Apple Silicon GPU (Metal) is available
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print(f'GPU available: {gpus[0].name}')
else:
    print('No GPU found — running on CPU. Install tensorflow-metal for Apple Silicon acceleration.')

GPU available: /physical_device:GPU:0

In [20]:
## Build ANN model
model=Sequential([
    tf.keras.Input(shape=(X_train.shape[1],)),
    Dense(64,activation='relu'),
    Dense(32,activation='relu'),
    Dense(1)  # Linear activation (default) for regression output
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

2026-06-07 01:04:14.204168: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M5
2026-06-07 01:04:14.204187: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 24.00 GB
2026-06-07 01:04:14.204192: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 8.88 GB
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1780774454.204202  778419 pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
I0000 00:00:1780774454.204217  778419 pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [21]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
## Setup the tensorboard
log_dir='regressionlogs/fit/'+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [23]:
## setup Early stopping
early_stopping_callbacks=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [24]:
## train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    batch_size=256,
    callbacks=[tensorflow_callback,early_stopping_callbacks]
)

Epoch 1/100

2026-06-07 01:04:14.943666: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 100431.0391 - mae: 100431.0391 - val_loss: 98725.4531 - val_mae: 98725.4531
Epoch 2/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 100430.3125 - mae: 100430.3125 - val_loss: 98724.4922 - val_mae: 98724.4922
Epoch 3/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100429.0312 - mae: 100429.0312 - val_loss: 98722.8594 - val_mae: 98722.8594
Epoch 4/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 100426.7891 - mae: 100426.7891 - val_loss: 98719.8906 - val_mae: 98719.8906
Epoch 5/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100422.9922 - mae: 100422.9922 - val_loss: 98715.0859 - val_mae: 98715.0859
Epoch 6/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100417.0234 - mae: 100417.0234 - val_loss: 98708.3750 - val_mae: 98708.3750
Epoch 7/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100408.9922 - mae: 100408.9922 - val_loss: 98699.0547 - val_mae: 98699.0547
Epoch 8/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100398.0078 - mae: 100398.0078 - val_loss: 98686.5938 - val_mae: 98686.5938
Epoch 9/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100382.7422 - mae: 100382.7422 - val_loss: 98669.4531 - val_mae: 98669.4531
Epoch 10/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100362.4297 - mae: 100362.4297 - val_loss: 98644.8281 - val_mae: 98644.8281
Epoch 11/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100333.1094 - mae: 100333.1094 - val_loss: 98610.8984 - val_mae: 98610.8984
Epoch 12/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100292.3125 - mae: 100292.3125 - val_loss: 98564.7031 - val_mae: 98564.7031
Epoch 13/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100237.7578 - mae: 100237.7578 - val_loss: 98504.6094 - val_mae: 98504.6094
Epoch 14/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 100171.0078 - mae: 100171.0078 - val_loss: 98429.6250 - val_mae: 98429.6250
Epoch 15/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 100088.5859 - mae: 100088.5859 - val_loss: 98344.5625 - val_mae: 98344.5625
Epoch 16/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 99993.2344 - mae: 99993.2344 - val_loss: 98244.6641 - val_mae: 98244.6641
Epoch 17/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 99883.3281 - mae: 99883.3281 - val_loss: 98133.0938 - val_mae: 98133.0938
Epoch 18/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 99760.9531 - mae: 99760.9531 - val_loss: 98007.3125 - val_mae: 98007.3125
Epoch 19/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 99628.2188 - mae: 99628.2188 - val_loss: 97870.0938 - val_mae: 97870.0938
Epoch 20/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 99483.2812 - mae: 99483.2812 - val_loss: 97722.0469 - val_mae: 97722.0469
Epoch 21/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 99328.1875 - mae: 99328.1875 - val_loss: 97566.2656 - val_mae: 97566.2656
Epoch 22/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 99163.4453 - mae: 99163.4453 - val_loss: 97401.6484 - val_mae: 97401.6484
Epoch 23/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98991.5781 - mae: 98991.5781 - val_loss: 97231.7578 - val_mae: 97231.7578
Epoch 24/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 98811.4688 - mae: 98811.4688 - val_loss: 97055.0703 - val_mae: 97055.0703
Epoch 25/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 98622.5469 - mae: 98622.5469 - val_loss: 96870.7344 - val_mae: 96870.7344
Epoch 26/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 98424.2109 - mae: 98424.2109 - val_loss: 96679.8984 - val_mae: 96679.8984
Epoch 27/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 98219.8750 - mae: 98219.8750 - val_loss: 96481.5703 - val_mae: 96481.5703
Epoch 28/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 98009.8438 - mae: 98009.8438 - val_loss: 96279.3438 - val_mae: 96279.3438
Epoch 29/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 97787.7734 - mae: 97787.7734 - val_loss: 96073.7422 - val_mae: 96073.7422
Epoch 30/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 97564.4219 - mae: 97564.4219 - val_loss: 95856.1953 - val_mae: 95856.1953
Epoch 31/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 97333.2344 - mae: 97333.2344 - val_loss: 95637.8203 - val_mae: 95637.8203
Epoch 32/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 97099.3438 - mae: 97099.3438 - val_loss: 95422.9453 - val_mae: 95422.9453
Epoch 33/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 96867.1719 - mae: 96867.1719 - val_loss: 95216.8047 - val_mae: 95216.8047
Epoch 34/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 96640.6953 - mae: 96640.6953 - val_loss: 95006.9531 - val_mae: 95006.9531
Epoch 35/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 96412.4375 - mae: 96412.4375 - val_loss: 94803.6016 - val_mae: 94803.6016
Epoch 36/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 96186.1953 - mae: 96186.1953 - val_loss: 94610.9062 - val_mae: 94610.9062
Epoch 37/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 95970.2266 - mae: 95970.2266 - val_loss: 94424.0781 - val_mae: 94424.0781
Epoch 38/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 95759.4766 - mae: 95759.4766 - val_loss: 94243.6562 - val_mae: 94243.6562
Epoch 39/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 95548.9297 - mae: 95548.9297 - val_loss: 94069.9375 - val_mae: 94069.9375
Epoch 40/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 95356.8750 - mae: 95356.8750 - val_loss: 93898.7891 - val_mae: 93898.7891
Epoch 41/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 95163.4297 - mae: 95163.4297 - val_loss: 93731.2656 - val_mae: 93731.2656
Epoch 42/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 94975.6953 - mae: 94975.6953 - val_loss: 93574.0781 - val_mae: 93574.0781
Epoch 43/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 94801.4219 - mae: 94801.4219 - val_loss: 93421.6016 - val_mae: 93421.6016
Epoch 44/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 94641.5547 - mae: 94641.5547 - val_loss: 93276.7969 - val_mae: 93276.7969
Epoch 45/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 94488.7734 - mae: 94488.7734 - val_loss: 93141.8750 - val_mae: 93141.8750
Epoch 46/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 94353.4531 - mae: 94353.4531 - val_loss: 93019.5078 - val_mae: 93019.5078
Epoch 47/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 94231.2656 - mae: 94231.2656 - val_loss: 92904.3359 - val_mae: 92904.3359
Epoch 48/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 94121.4375 - mae: 94121.4375 - val_loss: 92798.8984 - val_mae: 92798.8984
Epoch 49/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 94024.9609 - mae: 94024.9609 - val_loss: 92702.4922 - val_mae: 92702.4922
Epoch 50/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93939.0156 - mae: 93939.0156 - val_loss: 92613.9375 - val_mae: 92613.9375
Epoch 51/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93860.2500 - mae: 93860.2500 - val_loss: 92542.3516 - val_mae: 92542.3516
Epoch 52/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93792.5469 - mae: 93792.5469 - val_loss: 92486.4062 - val_mae: 92486.4062
Epoch 53/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 93734.4453 - mae: 93734.4453 - val_loss: 92442.6875 - val_mae: 92442.6875
Epoch 54/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 93683.0391 - mae: 93683.0391 - val_loss: 92404.5859 - val_mae: 92404.5859
Epoch 55/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 93632.6328 - mae: 93632.6328 - val_loss: 92369.7734 - val_mae: 92369.7734
Epoch 56/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 93591.6641 - mae: 93591.6641 - val_loss: 92347.8828 - val_mae: 92347.8828
Epoch 57/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93549.8828 - mae: 93549.8828 - val_loss: 92328.7734 - val_mae: 92328.7734
Epoch 58/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93505.9844 - mae: 93505.9844 - val_loss: 92302.7578 - val_mae: 92302.7578
Epoch 59/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93465.2031 - mae: 93465.2031 - val_loss: 92280.9609 - val_mae: 92280.9609
Epoch 60/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 93439.6016 - mae: 93439.6016 - val_loss: 92263.0234 - val_mae: 92263.0234
Epoch 61/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 93413.5859 - mae: 93413.5859 - val_loss: 92245.8984 - val_mae: 92245.8984
Epoch 62/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93380.3047 - mae: 93380.3047 - val_loss: 92225.8906 - val_mae: 92225.8906
Epoch 63/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93354.0078 - mae: 93354.0078 - val_loss: 92202.2344 - val_mae: 92202.2344
Epoch 64/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93327.3125 - mae: 93327.3125 - val_loss: 92179.6641 - val_mae: 92179.6641
Epoch 65/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 93296.4453 - mae: 93296.4453 - val_loss: 92151.4297 - val_mae: 92151.4297
Epoch 66/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93255.6719 - mae: 93255.6719 - val_loss: 92115.8438 - val_mae: 92115.8438
Epoch 67/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93223.2031 - mae: 93223.2031 - val_loss: 92087.6641 - val_mae: 92087.6641
Epoch 68/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93190.3438 - mae: 93190.3438 - val_loss: 92057.9922 - val_mae: 92057.9922
Epoch 69/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 93149.3125 - mae: 93149.3125 - val_loss: 92016.7812 - val_mae: 92016.7812
Epoch 70/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 93109.6172 - mae: 93109.6172 - val_loss: 91983.8750 - val_mae: 91983.8750
Epoch 71/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 93073.4688 - mae: 93073.4688 - val_loss: 91948.9844 - val_mae: 91948.9844
Epoch 72/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 93034.3984 - mae: 93034.3984 - val_loss: 91908.7500 - val_mae: 91908.7500
Epoch 73/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92995.9453 - mae: 92995.9453 - val_loss: 91872.5156 - val_mae: 91872.5156
Epoch 74/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92951.1484 - mae: 92951.1484 - val_loss: 91828.3359 - val_mae: 91828.3359
Epoch 75/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92900.8516 - mae: 92900.8516 - val_loss: 91776.7812 - val_mae: 91776.7812
Epoch 76/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92856.7969 - mae: 92856.7969 - val_loss: 91740.7266 - val_mae: 91740.7266
Epoch 77/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92814.0078 - mae: 92814.0078 - val_loss: 91692.2109 - val_mae: 91692.2109
Epoch 78/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92769.9766 - mae: 92769.9766 - val_loss: 91652.6719 - val_mae: 91652.6719
Epoch 79/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92731.3984 - mae: 92731.3984 - val_loss: 91610.5078 - val_mae: 91610.5078
Epoch 80/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92680.4297 - mae: 92680.4297 - val_loss: 91558.7656 - val_mae: 91558.7656
Epoch 81/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92641.4375 - mae: 92641.4375 - val_loss: 91518.6406 - val_mae: 91518.6406
Epoch 82/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92589.6875 - mae: 92589.6875 - val_loss: 91462.8750 - val_mae: 91462.8750
Epoch 83/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92542.5703 - mae: 92542.5703 - val_loss: 91421.3438 - val_mae: 91421.3438
Epoch 84/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92498.2969 - mae: 92498.2969 - val_loss: 91372.8516 - val_mae: 91372.8516
Epoch 85/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92440.8125 - mae: 92440.8125 - val_loss: 91308.1250 - val_mae: 91308.1250
Epoch 86/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92395.4297 - mae: 92395.4297 - val_loss: 91262.0781 - val_mae: 91262.0781
Epoch 87/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92348.1797 - mae: 92348.1797 - val_loss: 91215.1875 - val_mae: 91215.1875
Epoch 88/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92305.8047 - mae: 92305.8047 - val_loss: 91170.2109 - val_mae: 91170.2109
Epoch 89/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92263.2266 - mae: 92263.2266 - val_loss: 91121.1328 - val_mae: 91121.1328
Epoch 90/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92203.8516 - mae: 92203.8516 - val_loss: 91058.5859 - val_mae: 91058.5859
Epoch 91/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92156.4531 - mae: 92156.4531 - val_loss: 91011.7344 - val_mae: 91011.7344
Epoch 92/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92109.0312 - mae: 92109.0312 - val_loss: 90957.3828 - val_mae: 90957.3828
Epoch 93/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 92057.5312 - mae: 92057.5312 - val_loss: 90905.8125 - val_mae: 90905.8125
Epoch 94/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 92015.4297 - mae: 92015.4297 - val_loss: 90863.3438 - val_mae: 90863.3438
Epoch 95/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 91970.6484 - mae: 91970.6484 - val_loss: 90813.9531 - val_mae: 90813.9531
Epoch 96/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 91929.7109 - mae: 91929.7109 - val_loss: 90771.2031 - val_mae: 90771.2031
Epoch 97/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 91882.1953 - mae: 91882.1953 - val_loss: 90722.0625 - val_mae: 90722.0625
Epoch 98/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 91839.6406 - mae: 91839.6406 - val_loss: 90677.1250 - val_mae: 90677.1250
Epoch 99/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 91799.1719 - mae: 91799.1719 - val_loss: 90634.9297 - val_mae: 90634.9297
Epoch 100/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 91754.6484 - mae: 91754.6484 - val_loss: 90584.9141 - val_mae: 90584.9141

In [25]:
model.save('regression_model.keras')

In [26]:
%load_ext tensorboard

In [27]:
%tensorboard --logdir regressionlogs/fit